#include "comC.h"

extM(ac)

mX(ac) {
    { GDK_KEY_q,          "ᗇ"  },
    { GDK_KEY_w,          "ᖻ"  },
    { GDK_KEY_e,          "ᘺ"  },
    { GDK_KEY_r,          "ᗍ"  },
    { GDK_KEY_t,          "ᖸ"  },
    { GDK_KEY_y,          "ᗺ"  },
    { GDK_KEY_u,          "ᘆ"  },
    { GDK_KEY_i,          "ᕸ"  },
    { GDK_KEY_o,          "ᖺ"  },
    { GDK_KEY_p,          "ឞ"  },
    { GDK_KEY_a,          "ᘠ"  },
    { GDK_KEY_s,          "ᡮ"  },
    { GDK_KEY_d,          "ᕴ"  },
    { GDK_KEY_f,          "ᕵ"  },
    { GDK_KEY_g,          "ᢊ"  },
    { GDK_KEY_h,          "ᘾ"  },
    { GDK_KEY_j,          "ᕳ"  },
    { GDK_KEY_k,          "ᛪ"  },
    { GDK_KEY_l,          "ᖫ"  },
    { GDK_KEY_z,          "ᖀ"  },
    { GDK_KEY_x,          "ଉ"  },
    { GDK_KEY_c,          "ᘂ"  },
    { GDK_KEY_v,          "ᖲ"  },
    { GDK_KEY_b,          "ᕶ"  },
    { GDK_KEY_n,          "ᖕ"  },
    { GDK_KEY_m,          "ᢐ"  },

    { GDK_KEY_Tab,         "ꗖ"  },
    { GDK_KEY_bracketleft, "ᰞ"},
    { GDK_KEY_bracketright, "ஸ"},
    { GDK_KEY_semicolon,   "ꧦ"},
    { GDK_KEY_apostrophe,  "ៗ"},
    { GDK_KEY_comma,       "ꤺ"},
    { GDK_KEY_period,      "ꞯ"},
    { GDK_KEY_slash,       "Ꞌ"},
    { GDK_KEY_Return,      "ꦐ"},

    { GDK_KEY_Shift_L,    ""  }, //Dummy,
    { GDK_KEY_Shift_R,    ""  }, //Dummy,
};

mY(ac) {
    { GDK_KEY_q,          "ᡱ"  },
    { GDK_KEY_w,          "ᤂ"  },
    { GDK_KEY_e,          "ᛨ"  },
    { GDK_KEY_r,          "ᦔ"  },
    { GDK_KEY_t,          "ᜅ"  },
    { GDK_KEY_y,          "ᢌ"  },
    { GDK_KEY_u,          "ᝏ"  },
    { GDK_KEY_i,          "ᱳ"  },
    { GDK_KEY_o,          "ᢏ"  },
    { GDK_KEY_p,          "ᱍ"  },
    { GDK_KEY_a,          "ᱚ"  },
    { GDK_KEY_s,          "ᢕ"  },
    { GDK_KEY_d,          "ᢵ"  },
    { GDK_KEY_f,          "ᛎ"  },
    { GDK_KEY_g,          "ᢋ"  },
    { GDK_KEY_h,          "ᢈ"  },
    { GDK_KEY_j,          "ᠪ"  },
    { GDK_KEY_k,          "ᖏ"  },
    { GDK_KEY_l,          "ᯂ"  },
    { GDK_KEY_z,          "ᢒ"  },
    { GDK_KEY_x,          "ᜤ"  },
    { GDK_KEY_c,          "ᛲ"  },
    { GDK_KEY_v,          "ⶢ"  },
    { GDK_KEY_b,          "ង"  },
    { GDK_KEY_n,          "ᥑ"  },
    { GDK_KEY_m,          "ᢑ"  },

    { GDK_KEY_Tab,         "Ꞃ"  },
    { GDK_KEY_braceleft, "Ꜯ"},
    { GDK_KEY_braceright, "ꜭ"},
    { GDK_KEY_colon,   "ꪣ"},
    { GDK_KEY_quotedbl,  "ꗔ"},
    { GDK_KEY_less,       "ꤻ"},
    { GDK_KEY_greater,       "ꤱ"},
    { GDK_KEY_question,      "Ɥ"},
    { GDK_KEY_Return,      "ꦝ"},

    { GDK_KEY_Shift_L,    ""  }, //Dummy,
    { GDK_KEY_Shift_R,    ""  }, //Dummy,
};
