#include "comC.h"

extM(af)

mX(af) {
    { GDK_KEY_q,          "Ḝ"  },
    { GDK_KEY_w,          "ᬊ"  },
    { GDK_KEY_e,          "ṏ"  },
    { GDK_KEY_r,          "ᣩ"  },
    { GDK_KEY_t,          "Ⱁ"  },
    { GDK_KEY_y,          "ᩂ"  },
    { GDK_KEY_u,          "ᯜ"  },
    { GDK_KEY_i,          "Ⲗ"  },
    { GDK_KEY_o,          "ᬏ"  },
    { GDK_KEY_p,          "ᬅ"  },
    { GDK_KEY_a,          "Ṕ"  },
    { GDK_KEY_s,          "ᢔ"  },
    { GDK_KEY_d,          "ᢼ"  },
    { GDK_KEY_f,          "ⳡ"  },
    { GDK_KEY_g,          "ᣌ"  },
    { GDK_KEY_h,          "ᬯ"  },
    { GDK_KEY_j,          "ᢺ"  },
    { GDK_KEY_k,          "ᥚ"  },
    { GDK_KEY_l,          "ᤋ"  },
    { GDK_KEY_z,          "ᣃ"  },
    { GDK_KEY_x,          "ᣰ"  },
    { GDK_KEY_c,          "ᥙ"  },
    { GDK_KEY_v,          "ᣮ"  },
    { GDK_KEY_b,          "ઽ"  },
    { GDK_KEY_n,          "ḋ"  },
    { GDK_KEY_m,          "ᔧ"  },

    { GDK_KEY_Tab,         "Ⳮ"  },
    { GDK_KEY_bracketleft, "ἳ"},
    { GDK_KEY_bracketright, "ᾶ"},
    { GDK_KEY_semicolon,   "ⴙ"},
    { GDK_KEY_apostrophe,  "ẳ"},
    { GDK_KEY_comma,       "Ὣ"},
    { GDK_KEY_period,      "Ჽ"},
    { GDK_KEY_slash,       "ꛣ"},
    { GDK_KEY_Return,      "𐔌"},

    { GDK_KEY_Shift_L,    ""  }, //Dummy,
    { GDK_KEY_Shift_R,    ""  }, //Dummy,
};

mY(af) {
    { GDK_KEY_q,          "ḝ"  },
    { GDK_KEY_w,          "𐠙"  },
    { GDK_KEY_e,          "Ṑ"  },
    { GDK_KEY_r,          "ᤊ"  },
    { GDK_KEY_t,          "ⶒ"  },
    { GDK_KEY_y,          "Ằ"  },
    { GDK_KEY_u,          "ᴅ"  },
    { GDK_KEY_i,          "ⲗ"  },
    { GDK_KEY_o,          "ᱷ"  },
    { GDK_KEY_p,          "ḛ"  },
    { GDK_KEY_a,          "ṕ"  },
    { GDK_KEY_s,          "ᯗ"  },
    { GDK_KEY_d,          "ᤞ"  },
    { GDK_KEY_f,          "ⳣ"  },
    { GDK_KEY_g,          "Ẻ"  },
    { GDK_KEY_h,          "ᬰ"  },
    { GDK_KEY_j,          "ḃ"  },
    { GDK_KEY_k,          "Კ"  },
    { GDK_KEY_l,          "𐓛"  },
    { GDK_KEY_z,          "ᤉ"  },
    { GDK_KEY_x,          "Ế"  },
    { GDK_KEY_c,          "ᦖ"  },
    { GDK_KEY_v,          "ⵘ"  },
    { GDK_KEY_b,          "ᰕ"  },
    { GDK_KEY_n,          "Ḍ"  },
    { GDK_KEY_m,          "ᥕ"  },

    { GDK_KEY_Tab,         "ⴗ"  },
    { GDK_KEY_braceleft, "ꩆ"},
    { GDK_KEY_braceright, "ⲡ"},
    { GDK_KEY_colon,   "𐓓"},
    { GDK_KEY_quotedbl,  "ặ"},
    { GDK_KEY_less,       "ῒ"},
    { GDK_KEY_greater,       "ᾫ"},
    { GDK_KEY_question,      "ꛤ"},
    { GDK_KEY_Return,      "𐅕"},

    { GDK_KEY_Shift_L,    ""  }, //Dummy,
    { GDK_KEY_Shift_R,    ""  }, //Dummy,
};
