#include "comC.h"

extM(ag)

mX(ag) {
    { GDK_KEY_q,          "ᔩ"  },
    { GDK_KEY_w,          "ಇ"  },
    { GDK_KEY_e,          "ᐄ"  },
    { GDK_KEY_r,          "ᑝ"  },
    { GDK_KEY_t,          "ᔫ"  },
    { GDK_KEY_y,          "ᔥ"  },
    { GDK_KEY_u,          "ဦ"  },
    { GDK_KEY_i,          "ᐣ"  },
    { GDK_KEY_o,          "ᒟ"  },
    { GDK_KEY_p,          "ፆ"  },
    { GDK_KEY_a,          "ᐗ"  },
    { GDK_KEY_s,          "ᔤ"  },
    { GDK_KEY_d,          "ᔦ"  },
    { GDK_KEY_f,          "ᓸ"  },
    { GDK_KEY_g,          "ፖ"  },
    { GDK_KEY_h,          "ष"  },
    { GDK_KEY_j,          "ᡣ"  },
    { GDK_KEY_k,          "ጭ"  },
    { GDK_KEY_l,          "ව"  },
    { GDK_KEY_z,          "ᐂ"  },
    { GDK_KEY_x,          "ጠ"  },
    { GDK_KEY_c,          "ፔ"  },
    { GDK_KEY_v,          "ᔨ"  },
    { GDK_KEY_b,          "ᏽ"  },
    { GDK_KEY_n,          "ꙫ"  },
    { GDK_KEY_m,          "ꛌ"  },

    { GDK_KEY_Tab,         "ⲉ"  },
    { GDK_KEY_bracketleft, "ᦏ"},
    { GDK_KEY_bracketright, "ᨐ"},
    { GDK_KEY_semicolon,   "ᦇ"},
    { GDK_KEY_apostrophe,  "ጋ"},
    { GDK_KEY_comma,       "ᳩ"},
    { GDK_KEY_period,      "Ჿ"},
    { GDK_KEY_slash,       "ⴘ"},
    { GDK_KEY_Return,      "𓆭"},

    { GDK_KEY_Shift_L,    ""  }, //Dummy,
    { GDK_KEY_Shift_R,    ""  }, //Dummy,
};

mY(ag) {
    { GDK_KEY_q,          "ᔮ"  },
    { GDK_KEY_w,          "ᙄ"  },
    { GDK_KEY_e,          "ᛱ"  },
    { GDK_KEY_r,          "ᘇ"  },
    { GDK_KEY_t,          "ᚯ"  },
    { GDK_KEY_y,          "ឫ"  },
    { GDK_KEY_u,          "ᔸ"  },
    { GDK_KEY_i,          "ᗨ"  },
    { GDK_KEY_o,          "ᙒ"  },
    { GDK_KEY_p,          "ᙶ"  },
    { GDK_KEY_a,          "ថ"  },
    { GDK_KEY_s,          "ᚤ"  },
    { GDK_KEY_d,          "ꙛ"  },
    { GDK_KEY_f,          "ᗒ"  },
    { GDK_KEY_g,          "ᚂ"  },
    { GDK_KEY_h,          "ᔪ"  },
    { GDK_KEY_j,          "ᡤ"  },
    { GDK_KEY_k,          "ឪ"  },
    { GDK_KEY_l,          "ᕖ"  },
    { GDK_KEY_z,          "ᘉ"  },
    { GDK_KEY_x,          "ᛣ"  },
    { GDK_KEY_c,          "ᔻ"  },
    { GDK_KEY_v,          "ᗑ"  },
    { GDK_KEY_b,          "ᚅ"  },
    { GDK_KEY_n,          "ᙅ"  },
    { GDK_KEY_m,          "វ"  },

    { GDK_KEY_Tab,         "ꬿ"  },
    { GDK_KEY_braceleft, "ᮋ"},
    { GDK_KEY_braceright, "ᨑ"},
    { GDK_KEY_colon,   "ᦍ"},
    { GDK_KEY_quotedbl,  "ᚑ"},
    { GDK_KEY_less,       "Ḑ"},
    { GDK_KEY_greater,       "ḏ"},
    { GDK_KEY_question,      "ꚲ"},
    { GDK_KEY_Return,      "ꢞ"},

    { GDK_KEY_Shift_L,    ""  }, //Dummy,
    { GDK_KEY_Shift_R,    ""  }, //Dummy,
};
