#include "comC.h"

extM(bu)

mX(bu) {
    { GDK_KEY_q,          "𒂢"  },
    { GDK_KEY_w,          "𒑙"  },
    { GDK_KEY_e,          "𐜫"  },
    { GDK_KEY_r,          "𐤷"  },
    { GDK_KEY_t,          "𐡎"  },
    { GDK_KEY_y,          "𐜰"  },
    { GDK_KEY_u,          "𐣢"  },
    { GDK_KEY_i,          "𒈗"  },
    { GDK_KEY_o,          "𒈣"  },
    { GDK_KEY_p,          "𐡀"  },
    { GDK_KEY_a,          "𐜮"  },
    { GDK_KEY_s,          "𐠯"  },
    { GDK_KEY_d,          "𒉝"  },
    { GDK_KEY_f,          "𐤑"  },
    { GDK_KEY_g,          "𐝇"  },
    { GDK_KEY_h,          "𒆾"  },
    { GDK_KEY_j,          "𒉔"  },
    { GDK_KEY_k,          "𓃃"  },
    { GDK_KEY_l,          "𒀎"  },
    { GDK_KEY_z,          "𐨣"  },
    { GDK_KEY_x,          "𐨩"  },
    { GDK_KEY_c,          "𐨢"  },
    { GDK_KEY_v,          "𒈎"  },
    { GDK_KEY_b,          "𒅊"  },
    { GDK_KEY_n,          "𒈍"  },
    { GDK_KEY_m,          "𐜵"  },

    { GDK_KEY_Tab,         "𒉳"  },
    { GDK_KEY_bracketleft, "𒑨"},
    { GDK_KEY_bracketright, "𓅡"},
    { GDK_KEY_semicolon,   "𓀤"},
    { GDK_KEY_apostrophe,  "𐦕"},
    { GDK_KEY_comma,       "𓆩"},
    { GDK_KEY_period,      "𓏯"},
    { GDK_KEY_slash,       "𒔄"},
    { GDK_KEY_Return,      "𐢃"},

    { GDK_KEY_Shift_L,    ""  }, //Dummy,
    { GDK_KEY_Shift_R,    ""  }, //Dummy,
};

mY(bu) {
    { GDK_KEY_q,          "𒑄"  },
    { GDK_KEY_w,          "𓁗"  },
    { GDK_KEY_e,          "𓀡"  },
    { GDK_KEY_r,          "𓁙"  },
    { GDK_KEY_t,          "𒒼"  },
    { GDK_KEY_y,          "𓅺"  },
    { GDK_KEY_u,          "𒉭"  },
    { GDK_KEY_i,          "𓅧"  },
    { GDK_KEY_o,          "𒕂"  },
    { GDK_KEY_p,          "𓀖"  },
    { GDK_KEY_a,          "𒃜"  },
    { GDK_KEY_s,          "𓃟"  },
    { GDK_KEY_d,          "𓀆"  },
    { GDK_KEY_f,          "𓀎"  },
    { GDK_KEY_g,          "𓁅"  },
    { GDK_KEY_h,          "𓄏"  },
    { GDK_KEY_j,          "𒔿"  },
    { GDK_KEY_k,          "𓈻"  },
    { GDK_KEY_l,          "𒇯"  },
    { GDK_KEY_z,          "𓁍"  },
    { GDK_KEY_x,          "ꧾ"  },
    { GDK_KEY_c,          "𓀑"  },
    { GDK_KEY_v,          "𒈛"  },
    { GDK_KEY_b,          "𒐇"  },
    { GDK_KEY_n,          "𒎄"  },
    { GDK_KEY_m,          "𒑞"  },

    { GDK_KEY_Tab,         "𓅍"  },
    /* { GDK_KEY_braceleft, ""}, */
    { GDK_KEY_braceright, "𓅣"},
    { GDK_KEY_colon,   "𓀰"},
    { GDK_KEY_quotedbl,  "𓄄"},
    { GDK_KEY_less,       "𓎫"},
    { GDK_KEY_greater,       "𓏰"},
    { GDK_KEY_question,      "𓀔"},
    { GDK_KEY_Return,      "𓀧"},

    { GDK_KEY_Shift_L,    ""  }, //Dummy,
    { GDK_KEY_Shift_R,    ""  }, //Dummy,
};
