#include "comC.h"

extM(eu)

mX(eu) {
    { GDK_KEY_q,          "𐔑"  },
    { GDK_KEY_w,          "𐔥"  },
    { GDK_KEY_e,          "𐌴"  },
    { GDK_KEY_r,          "𐑑"  },
    { GDK_KEY_t,          "𐌞"  },
    { GDK_KEY_y,          "𐑯"  },
    { GDK_KEY_u,          "𐎧"  },
    { GDK_KEY_i,          "𐔦"  },
    { GDK_KEY_o,          "𐒿"  },
    { GDK_KEY_p,          "𐒖"  },
    { GDK_KEY_a,          "𐛽"  },
    { GDK_KEY_s,          "𐎪"  },
    { GDK_KEY_d,          "𐔍"  },
    { GDK_KEY_f,          "𐃡"  },
    { GDK_KEY_g,          "𐐌"  },
    { GDK_KEY_h,          "𐊓"  },
    { GDK_KEY_j,          "𐋄"  },
    { GDK_KEY_k,          "𐍪"  },
    { GDK_KEY_l,          "𐓵"  },
    { GDK_KEY_z,          "𐎍"  },
    { GDK_KEY_x,          "𐊡"  },
    { GDK_KEY_c,          "𐍨"  },
    { GDK_KEY_v,          "𐍡"  },
    { GDK_KEY_b,          "𐌰"  },
    { GDK_KEY_n,          "𐘓"  },
    { GDK_KEY_m,          "𐔅"  },

    { GDK_KEY_Tab,         "𐙤"  },
    { GDK_KEY_bracketleft, "𐔷"},
    { GDK_KEY_bracketright, "𐘭"},
    { GDK_KEY_semicolon,   "𐔧"},
    { GDK_KEY_apostrophe,  "𐛫"},
    { GDK_KEY_comma,       "𐚲"},
    { GDK_KEY_period,      "𐚖"},
    { GDK_KEY_slash,       "𐛢"},
    { GDK_KEY_Return,      "𐘚"},

    { GDK_KEY_Shift_L,    ""  }, //Dummy,
    { GDK_KEY_Shift_R,    ""  }, //Dummy,
};

mY(eu) {
    { GDK_KEY_q,          "𔘝"  },
    { GDK_KEY_w,          "𐰳"  },
    { GDK_KEY_e,          "𐙂"  },
    { GDK_KEY_r,          "𐑒"  },
    { GDK_KEY_t,          "𐐈"  },
    { GDK_KEY_y,          "𐑰"  },
    { GDK_KEY_u,          "𐑭"  },
    { GDK_KEY_i,          "𐡒"  },
    { GDK_KEY_o,          "𐩴"  },
    { GDK_KEY_p,          "𐱈"  },
    { GDK_KEY_a,          "𐐁"  },
    { GDK_KEY_s,          "𐱆"  },
    { GDK_KEY_d,          "𐔎"  },
    { GDK_KEY_f,          "𐰚"  },
    { GDK_KEY_g,          "𐕎"  },
    { GDK_KEY_h,          "𐘀"  },
    { GDK_KEY_j,          "𐍤"  },
    { GDK_KEY_k,          "𐍫"  },
    { GDK_KEY_l,          "𐲮"  },
    { GDK_KEY_z,          "𐚍"  },
    { GDK_KEY_x,          "𐩲"  },
    { GDK_KEY_c,          "𐐿"  },
    { GDK_KEY_v,          "𐑪"  },
    { GDK_KEY_b,          "𐌱"  },
    { GDK_KEY_n,          "𔗪"  },
    { GDK_KEY_m,          "𐔋"  },

    { GDK_KEY_Tab,         "𐠷"  },
    /* { GDK_KEY_braceleft, ""}, */
    { GDK_KEY_braceright, "𓐇"},
    { GDK_KEY_colon,   "𐡈"},
    { GDK_KEY_quotedbl,  "𓋫"},
    { GDK_KEY_less,       "𐚳"},
    { GDK_KEY_greater,       "𐚗"},
    { GDK_KEY_question,      "𑊱"},
    { GDK_KEY_Return,      "𐘰"},

    { GDK_KEY_Shift_L,    ""  }, //Dummy,
    { GDK_KEY_Shift_R,    ""  }, //Dummy,
};
