#include "comC.h"

extM(gb)

mX(gb) {
    { GDK_KEY_q,          "ᒅ"  },
    { GDK_KEY_w,          "ᘼ"  },
    { GDK_KEY_e,          "𐔈"  },
    { GDK_KEY_r,          "ឰ"  },
    { GDK_KEY_t,          "𐐆"  },
    { GDK_KEY_y,          "ꛙ"  },
    { GDK_KEY_u,          "ᙉ"  },
    { GDK_KEY_i,          "ಮ"  },
    { GDK_KEY_o,          "ᘶ"  },
    { GDK_KEY_p,          "ᦁ"  },
    { GDK_KEY_a,          "ᓳ"  },
    { GDK_KEY_s,          "ᙗ"  },
    { GDK_KEY_d,          "ᡴ"  },
    { GDK_KEY_f,          "ᚗ"  },
    { GDK_KEY_g,          "ᚳ"  },
    { GDK_KEY_h,          "𐒛"  },
    { GDK_KEY_j,          "ឆ"  },
    { GDK_KEY_k,          "ᮗ"  },
    { GDK_KEY_l,          "ᘋ"  },
    { GDK_KEY_z,          "ᘥ"  },
    { GDK_KEY_x,          "ច"  },
    { GDK_KEY_c,          "𐅊"  },
    { GDK_KEY_v,          "ᘔ"  },
    { GDK_KEY_b,          "ᘩ"  },
    { GDK_KEY_n,          "ᘷ"  },
    { GDK_KEY_m,          "ᖑ"  },

    { GDK_KEY_Tab,         "ꬺ"  },
    { GDK_KEY_bracketleft, "ꜗ"},
    { GDK_KEY_bracketright, "𖠬"},
    { GDK_KEY_semicolon,   "ᚼ"},
    { GDK_KEY_apostrophe,  "ꣶ"},
    { GDK_KEY_comma,       "ꨥ"},
    { GDK_KEY_period,      "ꢧ"},
    { GDK_KEY_slash,       "ᕔ"},
    { GDK_KEY_Return,      "ꣵ"},

    { GDK_KEY_Shift_L,    ""  }, //Dummy,
    { GDK_KEY_Shift_R,    ""  }, //Dummy,
};

mY(gb) {
    { GDK_KEY_q,          "ᰗ"  },
    { GDK_KEY_w,          "Ბ"  },
    { GDK_KEY_e,          "𐔉"  },
    { GDK_KEY_r,          "ꓢ"  },
    { GDK_KEY_t,          "𐔡"  },
    { GDK_KEY_y,          "ꛚ"  },
    { GDK_KEY_u,          "𑨀"  },
    { GDK_KEY_i,          "ᵎ"  },
    { GDK_KEY_o,          "𔔥"  },
    { GDK_KEY_p,          "ᱟ"  },
    { GDK_KEY_a,          "ṍ"  },
    { GDK_KEY_s,          "ꙕ"  },
    { GDK_KEY_d,          "ᶕ"  },
    { GDK_KEY_f,          "𐐙"  },
    { GDK_KEY_g,          "ⰷ"  },
    { GDK_KEY_h,          "𐒜"  },
    { GDK_KEY_j,          "ⴥ"  },
    { GDK_KEY_k,          "ጫ"  },
    { GDK_KEY_l,          "Ṏ"  },
    { GDK_KEY_z,          "Ⱄ"  },
    { GDK_KEY_x,          "ⶱ"  },
    { GDK_KEY_c,          "𐐾"  },
    { GDK_KEY_v,          "𔙄"  },
    { GDK_KEY_b,          "ἣ"  },
    { GDK_KEY_n,          "ꗂ"  },
    { GDK_KEY_m,          "ꬹ"  },

    { GDK_KEY_Tab,         "ꬻ"  },
    { GDK_KEY_braceleft, "Ḥ"},
    { GDK_KEY_braceright, "𖡋"},
    { GDK_KEY_colon,   "ꩵ"},
    { GDK_KEY_quotedbl,  "𓋬"},
    { GDK_KEY_less,       "ꨦ"},
    { GDK_KEY_greater,       "ꢲ"},
    { GDK_KEY_question,      "ꬓ"},
    { GDK_KEY_Return,      "ꦫ"},

    { GDK_KEY_Shift_L,    ""  }, //Dummy,
    { GDK_KEY_Shift_R,    ""  }, //Dummy,
};
