#include "comC.h"

extM(yu)

mX(yu) {
    { GDK_KEY_q,          "Ꙧ"  },
    { GDK_KEY_w,          "ꓙ"  },
    { GDK_KEY_e,          "ꡌ"  },
    { GDK_KEY_r,          "ꪞ"  },
    { GDK_KEY_t,          "ꭆ"  },
    { GDK_KEY_y,          "Ꞛ"  },
    { GDK_KEY_u,          "ꟻ"  },
    { GDK_KEY_i,          "ꚛ"  },
    { GDK_KEY_o,          "ꚤ"  },
    { GDK_KEY_p,          "ꔇ"  },
    { GDK_KEY_a,          "ꔈ"  },
    { GDK_KEY_s,          "ꙥ"  },
    { GDK_KEY_d,          "Ꙝ"  },
    { GDK_KEY_f,          "ꙧ"  },
    { GDK_KEY_g,          "ꚿ"  },
    { GDK_KEY_h,          "ⷑ"  },
    { GDK_KEY_j,          "ꗣ"  },
    { GDK_KEY_k,          "ꠛ"  },
    { GDK_KEY_l,          "ꨎ"  },
    { GDK_KEY_z,          "ꔶ"  },
    { GDK_KEY_x,          "Ꚇ"  },
    { GDK_KEY_c,          "ꦠ"  },
    { GDK_KEY_v,          "ꗢ"  },
    { GDK_KEY_b,          "ꤏ"  },
    { GDK_KEY_n,          "ꦦ"  },
    { GDK_KEY_m,          "ꙁ"  },

    { GDK_KEY_Tab,         "𐴋"  },
    { GDK_KEY_bracketleft, "𐁝"},
    { GDK_KEY_bracketright, "ꜳ"},
    { GDK_KEY_semicolon,   "ꪧ"},
    { GDK_KEY_apostrophe,  "ꬆ"},
    { GDK_KEY_comma,       "𐁄"},
    { GDK_KEY_period,      "ꤵ"},
    { GDK_KEY_slash,       "ꩲ"},
    { GDK_KEY_Return,      "ꯔ"},

    { GDK_KEY_Shift_L,    ""  }, //Dummy,
    { GDK_KEY_Shift_R,    ""  }, //Dummy,
};

mY(yu) {
    { GDK_KEY_q,          "ꟷ"  },
    { GDK_KEY_w,          "ꭀ"  },
    { GDK_KEY_e,          "ꯂ"  },
    { GDK_KEY_r,          "𐅲"  },
    { GDK_KEY_t,          "𐳃"  },
    { GDK_KEY_y,          "ꗳ"  },
    { GDK_KEY_u,          "𑨋"  },
    { GDK_KEY_i,          "ꛩ"  },
    { GDK_KEY_o,          "𐃥"  },
    { GDK_KEY_p,          "𑓄"  },
    { GDK_KEY_a,          "ꨗ"  },
    { GDK_KEY_s,          "Ꚃ"  },
    { GDK_KEY_d,          "ꙝ"  },
    { GDK_KEY_f,          "ꚧ"  },
    { GDK_KEY_g,          "ꩪ"  },
    { GDK_KEY_h,          "𑖣"  },
    { GDK_KEY_j,          "ꝗ"  },
    { GDK_KEY_k,          "𐅢"  },
    { GDK_KEY_l,          "𑘅"  },
    { GDK_KEY_z,          "ꗶ"  },
    { GDK_KEY_x,          "𐋉"  },
    { GDK_KEY_c,          "ꦡ"  },
    { GDK_KEY_v,          "𐃜"  },
    { GDK_KEY_b,          "ꤐ"  },
    { GDK_KEY_n,          "ꨙ"  },
    { GDK_KEY_m,          "ꬰ"  },

    { GDK_KEY_Tab,         "𐴌"  },
    { GDK_KEY_braceleft, "𑰫"},
    { GDK_KEY_braceright, "Ꜵ"},
    { GDK_KEY_colon,   "𒀀"},
    { GDK_KEY_quotedbl,  "𒀩"},
    { GDK_KEY_less,       "𑨡"},
    { GDK_KEY_greater,       "ꦜ"},
    { GDK_KEY_question,      "𑢶"},
    { GDK_KEY_Return,      "ꯘ"},

    { GDK_KEY_Shift_L,    ""  }, //Dummy,
    { GDK_KEY_Shift_R,    ""  }, //Dummy,
};
